apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubesphere-scheduling.name" . }}
  labels:
    {{- include "kubesphere-scheduling.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.apiserver }}
      targetPort: {{ .Values.service.port.apiserver }}
      protocol: TCP
      name: apiserver
    - port: 443
      targetPort: {{ .Values.service.port.controller }}
      protocol: TCP
      name: controller
  selector:
    {{- include "kubesphere-scheduling.selectorLabels" . | nindent 4 }}
