apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubesphere-schedule.name" . }}
  labels:
    {{- include "kubesphere-schedule.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.apiserver }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.controller }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "kubesphere-schedule.selectorLabels" . | nindent 4 }}
