{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "kubesphere-scheduling-cert"}}
{{- $existingWebHookConfig := lookup "admissionregistration.k8s.io/v1" "MutatingWebhookConfiguration" .Release.Namespace "kubesphere-scheduling"}}
{{- $ca := genCA "kubesphere-scheduling-ca" 3650 }}
{{- $cn := printf "kubesphere-scheduling" }}
{{- $altName1 := printf "kubesphere-scheduling.%s" .Release.Namespace }}
{{- $altName2 := printf "kubesphere-scheduling.%s.svc" .Release.Namespace }}
{{- $altName3 := printf "kubesphere-scheduling.%s.svc.cluster" .Release.Namespace }}
{{- $altName4 := printf "kubesphere-scheduling.%s.svc.cluster.local" .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2 $altName3 $altName4) 3650 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: kubesphere-scheduling-cert
  labels:
    {{- include "kubesphere-scheduling.labels" . | nindent 4 }}
data:
  {{ if $existingSecret }}tls.crt: {{ index $existingSecret.data "tls.crt" }}
  {{ else }}tls.crt: {{ b64enc $cert.Cert }}
  {{ end }}

  {{ if $existingSecret }}tls.key: {{ index $existingSecret.data "tls.key" }}
  {{ else }}tls.key: {{ b64enc $cert.Key }}
  {{ end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kubesphere-scheduling.name" . }}
  labels:
    app: {{ include "kubesphere-scheduling.name" . }}
webhooks:
- name: mutating.scheduling.kubesphere.io
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "kubesphere-scheduling.name" . }}
      path: "/mutate"
    caBundle: {{ if $existingWebHookConfig }}{{ (index $existingWebHookConfig.webhooks 0).clientConfig.caBundle }}{{ else }}{{ b64enc $ca.Cert }}{{ end }}
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    resources:
    - deployments
    - statefulsets
    - daemonsets
    operations:
    - "*"
  failurePolicy: Ignore
  sideEffects: None
  admissionReviewVersions: ["v1"]
