{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "kubesphere-schedule-cert"}}
{{- $existingWebHookConfig := lookup "admissionregistration.k8s.io/v1" "MutatingWebhookConfiguration" .Release.Namespace "kubesphere-schedule"}}
{{- $ca := genCA "kubesphere-schedule-ca" 3650 }}
{{- $cn := printf "kubesphere-schedule" }}
{{- $altName1 := printf "kubesphere-schedule.%s" .Release.Namespace }}
{{- $altName2 := printf "kubesphere-schedule.%s.svc" .Release.Namespace }}
{{- $altName3 := printf "kubesphere-schedule.%s.svc.cluster" .Release.Namespace }}
{{- $altName4 := printf "kubesphere-schedule.%s.svc.cluster.local" .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2 $altName3 $altName4) 3650 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: kubesphere-schedule-cert
  labels:
    {{- include "kubesphere-schedule.labels" . | nindent 4 }}
data:
  {{ if $existingSecret }}tls.crt: {{ index $existingSecret.data "tls.crt" }}
  {{ else }}tls.crt: {{ b64enc $cert.Cert }}
  {{ end }}

  {{ if $existingSecret }}tls.key: {{ index $existingSecret.data "tls.key" }}
  {{ else }}tls.key: {{ b64enc $cert.Key }}
  {{ end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kubesphere-schedule.fullname" . }}
  labels:
    app: {{ include "kubesphere-schedule.fullname" . }}
webhooks:
- name: mutating.kubeedge.kubesphere.io
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "kubesphere-schedule.fullname" . }}
      path: "/mutate"
    caBundle: {{ if $existingWebHookConfig }}{{ (index $existingWebHookConfig.webhooks 0).clientConfig.caBundle }}{{ else }}{{ b64enc $ca.Cert }}{{ end }}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    resources:
    - deployments
    operations:
    - CREATE
    - UPDATE
  - apiGroups:
      - ""
    apiVersions:
      - v1
    resources:
      - statefulsets
    operations:
      - CREATE
      - UPDATE
  failurePolicy: Ignore
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
