# permissions for end users to edit analysistasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: analysistask-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tmp
    app.kubernetes.io/part-of: tmp
    app.kubernetes.io/managed-by: kustomize
  name: analysistask-editor-role
rules:
- apiGroups:
  - schedule.kubesphere.io
  resources:
  - analysistasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - schedule.kubesphere.io
  resources:
  - analysistasks/status
  verbs:
  - get
