
apiVersion: scheduling.kubesphere.io/v1alpha1
kind: AnalysisTask
metadata:
  name: analysistask-wl
spec:
  type: Workload                        # This can only be "Deployment" or "Namespace".
  completionStrategy:
    completionStrategyType: Periodical  # This can only be "Once" or "Periodical".
    periodSeconds: 60                # analytics selected resources every 1 day
  resourceSelectors:                    # defines all the resources to be select with
    - kind: Deployment
      apiVersion: apps/v1
      name: cpu-stress