
apiVersion: schedule.kubesphere.io/v1alpha1
kind: AnalysisTask
metadata:
  name: analysistask-ns
spec:
  type: Namespace                        # This can only be "Deployment" or "Namespace".
  completionStrategy:
    completionStrategyType: Periodical  # This can only be "Once" or "Periodical".
    periodSeconds: 60                # analytics selected resources every 1 day
  resourceSelectors:                    # defines all the resources to be select with
    - kind: Namespace
      apiVersion: apps/v1
      name: default